# Documentation:
# https://docs.netlify.com/configure-builds/file-based-configuration

[build]
  publish = "client"

[functions]
  directory = "api"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index"
  status = 301
  force = true

[dev]
  port = 8080
  autoLaunch = true